


HILL_POLYGONS_PER_PAINT = 200
HILL_POLYGONS_N_VERTICES = 10

HILL_RED_MIN_VALUE = 0
HILL_RED_MAX_VALUE = 255
HILL_GREEN_MIN_VALUE = 0
HILL_GREEN_MAX_VALUE = 255
HILL_BLUE_MIN_VALUE = 0
HILL_BLUE_MAX_VALUE = 255
HILL_ALPHA_MIN_VALUE = 0
HILL_ALPHA_MAX_VALUE = 255

HILL_COLOR_MIN_VALUE = 0
HILL_COLOR_MAX_VALUE = 255

HILL_POLYGON_ORIGIN_TO_VERTICE_MAX_DISTANCE = 50

HILL_MUTATION_COLOR_DISTANCE = 1
HILL_MUTATION_CORNER_MOVE_RATE = 100
HILL_MUTATION_CORNER_ADD_RATE = 100
HILL_MUTATION_CORNER_REMOVE_RATE = 100
HILL_MUTATION_COLOR_CHANGE_RATE = 100


ECO_GEN_DEATH_RATIO = 0.3
ECO_NEW_BREEDS_RATIO = 0.2
ECO_NEW_RANDOM_RATIO = 0.1
ECO_ELIGIBLE_PARENTS_RATIO = 0.1



